# Generated by Django 3.1.1 on 2020-09-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20200914_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='detail',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='detail_text',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='e_mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
