# Generated by Django 3.1.1 on 2020-09-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20200915_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='photo',
        ),
    ]
